%% output data config

% imgFormat = 'png';
% imgFormat = 'pdf';
imgFormat = 'tiff';

saveOutputFigures = true;
% saveOutputFigures = false;

% N = 90; % size of the parcellation of the main results
% sortNodesBy = 'lobe'; % 'lobe' or 'func' or 'funclr'

N = 306; % size of the parcellation of the main results
sortNodesBy = 'func';

plotData = 'flip'; % 'raw', 'flip', 'zScoreToControls'if strcmp(plotData,'raw')
                       % 'raw' means no z-scoring at all
                       % 'flip' means the simulation data has been z-scored to controls and then flipped
                       % 'zScoreToControls' means no flipping occured
groupLabels = { 'LRTLE' }; % list of group labels that are going to be plotted

% plotData = 'zScoreToControls'; % 'raw', 'flip', 'zScoreToControls'
% groupLabels = { 'RTLE', 'LTLE' }; % list of group labels that are going to be plotted

% plotData = 'raw'; % 'raw' -> plot data without preprocessing; 'flip' -> plot data with RTLE flipped and grouped with LTLE; 'zScoreToControls' -> plot data that has been z-scored to controls (no flipping)

% thetaVal = [0,0.005,0.01,0.015,0.02];
% thetaVal = 0.01;
thetaVal = 0.015;

addpath('func');

nodeLabels = {'Hippocampus_R','Hippocampus_L','Thalamus_R','Thalamus_L','Amygdala_R','Amygdala_L','ParaHippocampal_R','ParaHippocampal_L'};

displayData = { 'raw', 'comm' }; % 'raw' -> full matrices; and/or 'comm' -> community data

%% input data config

% useFDR = 2; % false, true, or 2; if useFDR == 2, show t-test figures
useFDR = true; % false, true, or 2; if useFDR == 2, show t-test figures
% useFDR = 0.8; % ####### SET showDataColor=2 ############### effect size threshold (see below)

effectSizeField = 'Cohen_Mahal';
                % Cohen effect size threshold table (useFDR == effect size threshold)
                %Large        0.80    Cohen, 1988
                %Very large   1.20    Sawilowsky, 2009
                %Huge         2.00001     Sawilowsky, 2009
                % Sawilowsky, S (2009). "New effect size rules of thumb". Journal of Modern Applied Statistical Methods. 8 (2): 467–474. doi:10.22237/jmasm/1257035100. http://digitalcommons.wayne.edu/jmasm/vol8/iss2/26/

% effectSizeField = 'effsz';
                             % f sqr maybe? if it is f sqr, then
                             % f sqr >= 0.02 (small)
                             % f sqr >= 0.15 (medium)
                             % f sqr >= 0.35 (large) (Cohen 1988 book)  
                
% showDataColor = 2; % if showDataColor = 2 % color the effect sizes
showDataColor =  true; % ########### SET useFDR==TRUE ###################### color z-scores in the surface plots for nodes that pass the t-test
% showDataColor = false; % show only if z-score < or > than 0 for nodes that pass t-test in the surface map

%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%% 
%%%%%%%%%%%%%% the four variables below are used to decide which 'sim_data_*.mat' file (generated by processSpreadingData.m) should be used to plot the figure...
%%%%%%%%%%%%%% so in order to plot a figure with different configuration, you first need to process a new data set and then load it in plot_sim_data_func without relying
%%%%%%%%%%%%%% on the function plot_func.loadPlotData()
%%%%%%%%%%%%%% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%

% t-value threshold
tThresh = 0;%[0.4,0.6];%[0.6,0.75,0.85]; % percent of the diff(abs(minmax(t))) (show only 1 - tThresh t-values)

% useBinarySpTime = true;
useBinarySpTime = false;

splitTTest = true;
% splitTTest = false;

% zScoreIndividually = true;
zScoreIndividually = false;

ttestOnAvg = true;
% ttestOnAvg = false;

odirSuffix = '';
if islogical(useFDR) && useFDR
    odirSuffix = '_fdr';
end
if isnumeric(useFDR)
    if strcmpi(effectSizeField,'Cohen_Mahal')
        odirSuffix = ['_cohen',num2str(useFDR)];
    else
        odirSuffix = ['_effsz',num2str(useFDR)];
    end
end

%% in/out folders

programDir = 'D:\Dropbox\p\postdoc\programs\matlab\sirs';
dataDir = 'D:\Dropbox\p\postdoc\data\sirs\selected';
if isunix
    programDir = '/host/scarus/local_raid/mauricio/programs/matlab';
    dataDir = '/host/scarus/local_raid/mauricio/data/sirs/selected';
end