function [labL, labR, indL, indR] = getMTLNodeLabels(labels)
    indL = cellfun(@(x)~isempty(x),strfind(labels,'Hippocampus_L')) | ...
          cellfun(@(x)~isempty(x),strfind(labels,'Amygdala_L')) | ...
          cellfun(@(x)~isempty(x),strfind(labels,'ParaHippocampal_L'));
    labL = labels(indL);
    indL = find(indL);
    indR = cellfun(@(x)~isempty(x),strfind(labels,'Hippocampus_R')) | ...
          cellfun(@(x)~isempty(x),strfind(labels,'Amygdala_R')) | ...
          cellfun(@(x)~isempty(x),strfind(labels,'ParaHippocampal_R'));
    labR = labels(indR);
    indR = find(indR);
end